FEATURES : [
  '암의 위치', 
  '암의 개수', 
  '암의 장경', 
  'NG', 'HG', 'HG_score_1', 'HG_score_2', 'HG_score_3',
  'DCIS_or_LCIS_여부', 'DCIS_or_LCIS_type', 'T_category', 'ER',
  'ER_Allred_score', 'PR', 'PR_Allred_score', 'KI-67_LI_percent',
  'HER2',
  'HER2_IHC', 
  'HER2_SISH', 
  'HER2_SISH_ratio', 
  'BRCA_mutation'
]